# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/languages/go/
# https://docs.travis-ci.com/user/customizing-the-build/

language: go
git:
    depth: 1

install:
    - go get -v github.com/gohugoio/hugo

before_script:
    - rm -rf public 2> /dev/null

# script - run the build script
script:
    - hugo
    # - echo "$CNAME_URL" > public/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  verbose: true
  keep-history: true
  local-dir: public
  on:
    branch: master
  repo: fivestrong.github.io
  fqdn: linuxfunk.com
  target_branch: master
  email: fivestrong@live.com
  name: fivestrong
